#!/bin/bash
#xrandr --output HDMI-1 --rotate normal --reflect x
java -jar /home/pi/holoprism-1.0-SNAPSHOT.jar &
mpv --fs --osc=no --loop-playlist=yes ~/play/* --input-ipc-server=/tmp/mpvsocket

#TODO: wifi connect, screen configuration, ssh, bootstrap 
