#! /bin/sh
~/raspbian/autostart &

set -xv
exec 2>>~/bspwm.log

bspc monitor HDMI-1 -n 0 -d one 
bspc monitor HDMI-2 -n 1 -d two

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mpv desktop='two' state=fullscreen follow=off
bspc rule -a fx desktop='one' state=fullscreen follow=on
