#! /bin/bash
#### AUTOSTART ####


#### MONITORS ####

### DRACULA
bspc config normal_border_color "#282a36"
bspc config focused_border_color "#ff79c6"
bspc config presel_border_color "#44475a"

#### BSPWM configuration ####
bspc config focus_follows_pointer         true
bspc config border_width                  1
bspc config window_gap                    0
bspc config top_padding                   18
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config split_ratio                   0.60
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule --add mpv state=fullscrean desktop=^1 follow=on
