#! /bin/bash
#### AUTOSTART ####
autostart &


#### MONITORS ####
bspc monitor --reset-desktops       

### DRACULA
bspc config normal_border_color "#282a36"
bspc config focused_border_color "#ff79c6"
bspc config presel_border_color "#44475a"

#### BSPWM configuration ####
bspc config focus_follows_pointer         true
bspc config border_width                  1
bspc config window_gap                    0
bspc config top_padding                   18
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config split_ratio                   0.60
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule --add Emacs state=tiled

bspc rule --add cantata desktop=^7 follow=on
bspc rule --add LBRY desktop=^7 follow=on
bspc rule --add mpv state=floating desktop=^7 follow=on

bspc rule --add Steam --one-shot desktop=^6 follow=on
bspc rule --add Lutris desktop=^6 follow=on
bspc rule --add retroarch desktop=^6 follow=on
bspc rule --add Doomseeker desktop=^6 follow=on

bspc rule --add steam_app_238960 desktop=^5 follow=on state=fullscrean #poe
bspc rule --add "Dota 2" desktop=^5 follow=on state=fullscrean


bspc rule --add firefox desktop=^1 follow=on
bspc rule --add Brave-browser desktop=^1 follow=on
bspc rule --add qutebrowser desktop=^1 follow=on

bspc rule --add Blender desktop=^4 follow=on
bspc rule --add "Instant Meshes" desktop=^4 follow=on
bspc rule --add Inkscape desktop=^4 follow=on
bspc rule --add krita desktop=^4 follow=on
bspc rule --add meshroom desktop=^4 follow=on
bspc rule --add "GNU Image Manipulation Program" desktop=^4 follow=on
